version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: test_app
    links:
      - app-db
    ports:
      - "8000:8000"
  app-db:
    image: mariadb
    container_name: app_db
    restart: always
    ports:
      - "33066:3306"
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      MYSQL_ROOT_PASSWORD: test
